{% set name = "dbt-semantic-interfaces" %}
{% set version = "0.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
    sha256: dcedda6702ecabb633aa4e8ab3b1eb7f9c4301dcc0026076a4a0ef64f9e59cf0
  - url: https://github.com/dbt-labs/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: be2e07b395095bdee6d8627dc9df4634cfae4afbed792b3c28e36d61a635d372
    folder: tests

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<38]

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - pydantic >=1.10,<3
    - jsonschema >=4.0,<5
    - pyyaml >=6.0,<7
    - more-itertools >=8.0,<11.0
    - jinja2 >=3.1.3,<4
    - click >=7.0,<9.0
    - python-dateutil >=2.0,<3
    - importlib_metadata >=6.0,<7
    - typing-extensions >=4.4,<5

test:
  source_files:
    - tests
  imports:
    - dbt_semantic_interfaces
  commands:
    - pip check
    - pytest -vv tests
  requires:
    - pip
    - pytest >=7.3,<8
    - hypothesis >=6.87,<7

about:
  home: https://github.com/dbt-labs/dbt-semantic-interfaces
  summary: The shared semantic layer definitions that dbt-core and MetricFlow use
  description: |
    This repo contains the shared semantic classes, default validation, and tests designed to be used by both the dbt-core and MetricFlow projects. 
    By centralizing these shared resources, we aim to maintain consistency and reduce code duplication across both projects.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/dbt-labs/dbt-semantic-interfaces
  doc_url: https://github.com/dbt-labs/dbt-semantic-interfaces/blob/main/README.md

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/63495
    reason: Dependency for dbt-core
  recipe-maintainers:
    - ianaobi
  recipe-maintainers:
    - thewchan
    - maresb
